[package]
name                   = "sbpf-assembler"
description            = "SBPF Assembler"
version.workspace      = true

[dependencies]
num-derive = { workspace = true }
num-traits = { workspace = true }
anyhow = { workspace = true }